### ISSUE TITLE
Cannot install lambdapi via opam with ocaml 4.07.1

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#116]
14:04 ~ opam install lambdapi
The following dependencies couldn't be met:
  - lambdapi → earley-ocaml >= 1.0.2 → ocaml < 4.07.1
      base of this switch (use `--unlock-base' to force)

No solution found, exiting

**Comment by rlepigre** [comment]
It seems that I forgot to update `lambdapi.opam` (this is now fixed), but I don't know if this is related to your problem. You can try to do `opam remove earley earley-ocaml && opam install earley.2.0.0` before trying to compile `lambdapi`.

**Comment by fblanqui** [comment]
The problem is with earley-ocaml:

depends:      "ocaml" {>= "4.03.0" & <= "4.07.0"}

and lambdapi depends on earley-ocaml


Le 12/11/2018 à 14:44, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
No, not anymore.

**Comment by fblanqui** [comment]
Why do I still get this morning:

The following dependencies couldn't be met:
   - lambdapi → earley-ocaml >= 1.0.2 → ocaml < 4.07.1
       base of this switch (use `--unlock-base' to force)

No solution found, exiting

?

Le 12/11/2018 à 20:10, Rodolphe Lepigre a écrit :
